"""master config sim ops tables

Revision ID: 0002_master_config_sim_ops
Revises: 0001_baseline
Create Date: 2026-09-25 15:42:45.993947
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_master_config_sim_ops"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "config_office_configuration",
        sa.Column("config_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("simulation_yaml", sa.JSON(), nullable=False),
        sa.Column("organization_yaml", sa.JSON(), nullable=False),
        sa.Column("layout_yaml", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("config_id", name=op.f("pk_config_office_configuration")),
    )
    with op.batch_alter_table("config_office_configuration", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_config_office_configuration_content_hash"),
            ["content_hash"],
            unique=False,
        )

    op.create_table(
        "master_department",
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("department_id", name=op.f("pk_master_department")),
    )
    op.create_table(
        "master_organization",
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("org_id", name=op.f("pk_master_organization")),
    )
    op.create_table(
        "ops_ingestion_watermark",
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("watermark_value", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("source_name", name=op.f("pk_ops_ingestion_watermark")),
    )
    op.create_table(
        "ops_pipeline_run",
        sa.Column("pipeline_run_id", sa.String(length=36), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("pipeline_run_id", name=op.f("pk_ops_pipeline_run")),
    )
    op.create_table(
        "ops_source_status_snapshot",
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("snapshot_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("events_received", sa.BigInteger(), nullable=False),
        sa.Column("last_event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_processed", sa.BigInteger(), nullable=False),
        sa.Column("processing_failures", sa.BigInteger(), nullable=False),
        sa.Column("avg_latency_ms", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "source_name", "snapshot_at", name=op.f("pk_ops_source_status_snapshot")
        ),
    )
    op.create_table(
        "config_master_data_version",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("config_id", sa.String(length=36), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("employee_count", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["config_office_configuration.config_id"],
            name=op.f("fk_config_master_data_version_config_id_config_office_configuration"),
        ),
        sa.PrimaryKeyConstraint("version_id", name=op.f("pk_config_master_data_version")),
    )
    op.create_table(
        "master_building",
        sa.Column("building_id", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("max_occupancy", sa.Integer(), nullable=False),
        sa.Column("gross_area_sqm", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["master_organization.org_id"],
            name=op.f("fk_master_building_org_id_master_organization"),
        ),
        sa.PrimaryKeyConstraint("building_id", name=op.f("pk_master_building")),
    )
    op.create_table(
        "ops_pipeline_layer_count",
        sa.Column("pipeline_run_id", sa.String(length=36), nullable=False),
        sa.Column("layer", sa.String(), nullable=False),
        sa.Column("object_name", sa.String(), nullable=False),
        sa.Column("rows_total", sa.BigInteger(), nullable=False),
        sa.Column("rows_added", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["ops_pipeline_run.pipeline_run_id"],
            name=op.f("fk_ops_pipeline_layer_count_pipeline_run_id_ops_pipeline_run"),
        ),
        sa.PrimaryKeyConstraint(
            "pipeline_run_id", "layer", "object_name", name=op.f("pk_ops_pipeline_layer_count")
        ),
    )
    op.create_table(
        "master_floor",
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("building_id", sa.String(), nullable=False),
        sa.Column("floor_number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("max_occupancy", sa.Integer(), nullable=False),
        sa.Column("desk_policy", sa.String(), nullable=False),
        sa.Column("plan_width", sa.Float(), nullable=False),
        sa.Column("plan_height", sa.Float(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["master_building.building_id"],
            name=op.f("fk_master_floor_building_id_master_building"),
        ),
        sa.PrimaryKeyConstraint("floor_id", name=op.f("pk_master_floor")),
    )
    op.create_table(
        "sim_simulation_run",
        sa.Column("simulation_run_id", sa.String(length=36), nullable=False),
        sa.Column("config_id", sa.String(length=36), nullable=True),
        sa.Column("master_data_version", sa.String(length=36), nullable=True),
        sa.Column("config_snapshot", sa.JSON(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("sim_start_date", sa.Date(), nullable=False),
        sa.Column("sim_end_date", sa.Date(), nullable=True),
        sa.Column("initial_speed", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("wall_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("wall_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sim_time_reached", sa.DateTime(timezone=True), nullable=True),
        sa.Column("events_generated", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("truth_events", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["config_office_configuration.config_id"],
            name=op.f("fk_sim_simulation_run_config_id_config_office_configuration"),
        ),
        sa.ForeignKeyConstraint(
            ["master_data_version"],
            ["config_master_data_version.version_id"],
            name=op.f("fk_sim_simulation_run_master_data_version_config_master_data_version"),
        ),
        sa.PrimaryKeyConstraint("simulation_run_id", name=op.f("pk_sim_simulation_run")),
    )
    op.create_table(
        "master_access_point",
        sa.Column("access_point_id", sa.String(), nullable=False),
        sa.Column("building_id", sa.String(), nullable=False),
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["master_building.building_id"],
            name=op.f("fk_master_access_point_building_id_master_building"),
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_access_point_floor_id_master_floor"),
        ),
        sa.PrimaryKeyConstraint("access_point_id", name=op.f("pk_master_access_point")),
    )
    op.create_table(
        "master_team",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("home_floor_id", sa.String(), nullable=False),
        sa.Column("office_days", sa.JSON(), nullable=False),
        sa.Column("size_target", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["master_department.department_id"],
            name=op.f("fk_master_team_department_id_master_department"),
        ),
        sa.ForeignKeyConstraint(
            ["home_floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_team_home_floor_id_master_floor"),
        ),
        sa.PrimaryKeyConstraint("team_id", name=op.f("pk_master_team")),
    )
    op.create_table(
        "master_zone",
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("zone_type", sa.String(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("max_occupancy", sa.Integer(), nullable=False),
        sa.Column("area_sqm", sa.Float(), nullable=False),
        sa.Column("is_hvac_zone", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_zone_floor_id_master_floor"),
        ),
        sa.PrimaryKeyConstraint("zone_id", name=op.f("pk_master_zone")),
    )
    with op.batch_alter_table("master_zone", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_master_zone_floor_id"), ["floor_id"], unique=False)

    op.create_table(
        "sim_run_metrics_snapshot",
        sa.Column("simulation_run_id", sa.String(length=36), nullable=False),
        sa.Column("sim_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("employees_inside", sa.Integer(), nullable=False),
        sa.Column("occupied_desks", sa.Integer(), nullable=False),
        sa.Column("occupied_rooms", sa.Integer(), nullable=False),
        sa.Column("events_generated", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"],
            ["sim_simulation_run.simulation_run_id"],
            name=op.f("fk_sim_run_metrics_snapshot_simulation_run_id_sim_simulation_run"),
        ),
        sa.PrimaryKeyConstraint(
            "simulation_run_id", "sim_time", name=op.f("pk_sim_run_metrics_snapshot")
        ),
    )
    op.create_table(
        "sim_run_speed_change",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("simulation_run_id", sa.String(length=36), nullable=False),
        sa.Column("wall_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sim_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("old_speed", sa.Integer(), nullable=False),
        sa.Column("new_speed", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"],
            ["sim_simulation_run.simulation_run_id"],
            name=op.f("fk_sim_run_speed_change_simulation_run_id_sim_simulation_run"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sim_run_speed_change")),
    )
    op.create_table(
        "master_employee",
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("employee_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("department_id", sa.String(), nullable=False),
        sa.Column("job_role", sa.String(), nullable=False),
        sa.Column("manager_id", sa.String(), nullable=True),
        sa.Column("home_floor_id", sa.String(), nullable=False),
        sa.Column("preferred_zone_id", sa.String(), nullable=False),
        sa.Column("employment_type", sa.String(), nullable=False),
        sa.Column("work_mode", sa.String(), nullable=False),
        sa.Column("behavior_profile", sa.String(), nullable=False),
        sa.Column("active_flag", sa.Boolean(), nullable=False),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["master_department.department_id"],
            name=op.f("fk_master_employee_department_id_master_department"),
        ),
        sa.ForeignKeyConstraint(
            ["home_floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_employee_home_floor_id_master_floor"),
        ),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["master_employee.employee_id"],
            name=op.f("fk_master_employee_manager_id_master_employee"),
        ),
        sa.ForeignKeyConstraint(
            ["preferred_zone_id"],
            ["master_zone.zone_id"],
            name=op.f("fk_master_employee_preferred_zone_id_master_zone"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["master_team.team_id"],
            name=op.f("fk_master_employee_team_id_master_team"),
        ),
        sa.PrimaryKeyConstraint("employee_id", name=op.f("pk_master_employee")),
        sa.UniqueConstraint("email", name=op.f("uq_master_employee_email")),
    )
    with op.batch_alter_table("master_employee", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_master_employee_department_id"), ["department_id"], unique=False
        )
        batch_op.create_index("ix_master_employee_home_floor", ["home_floor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_master_employee_team_id"), ["team_id"], unique=False)

    op.create_table(
        "master_room",
        sa.Column("room_id", sa.String(), nullable=False),
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("room_type", sa.String(), nullable=False),
        sa.Column("area_subtype", sa.String(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("is_bookable", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_room_floor_id_master_floor"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["master_zone.zone_id"], name=op.f("fk_master_room_zone_id_master_zone")
        ),
        sa.PrimaryKeyConstraint("room_id", name=op.f("pk_master_room")),
    )
    with op.batch_alter_table("master_room", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_master_room_floor_id"), ["floor_id"], unique=False)

    op.create_table(
        "master_sensor",
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("sensor_type", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("poll_interval_s", sa.Integer(), nullable=False),
        sa.Column("installed_at", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_sensor_floor_id_master_floor"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["master_zone.zone_id"], name=op.f("fk_master_sensor_zone_id_master_zone")
        ),
        sa.PrimaryKeyConstraint("sensor_id", name=op.f("pk_master_sensor")),
    )
    with op.batch_alter_table("master_sensor", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_master_sensor_floor_id"), ["floor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_master_sensor_target_id"), ["target_id"], unique=False)

    op.create_table(
        "master_team_zone_allocation",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("share", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["master_team.team_id"],
            name=op.f("fk_master_team_zone_allocation_team_id_master_team"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["master_zone.zone_id"],
            name=op.f("fk_master_team_zone_allocation_zone_id_master_zone"),
        ),
        sa.PrimaryKeyConstraint("team_id", "zone_id", name=op.f("pk_master_team_zone_allocation")),
    )
    op.create_table(
        "master_workspace",
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("workspace_type", sa.String(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("has_sensor", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["floor_id"],
            ["master_floor.floor_id"],
            name=op.f("fk_master_workspace_floor_id_master_floor"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["master_zone.zone_id"],
            name=op.f("fk_master_workspace_zone_id_master_zone"),
        ),
        sa.PrimaryKeyConstraint("workspace_id", name=op.f("pk_master_workspace")),
    )
    with op.batch_alter_table("master_workspace", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_master_workspace_floor_id"), ["floor_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_master_workspace_zone_id"), ["zone_id"], unique=False)

    op.create_table(
        "master_employee_work_pattern",
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("iso_weekday", sa.Integer(), nullable=False),
        sa.Column("planned_mode", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["master_employee.employee_id"],
            name=op.f("fk_master_employee_work_pattern_employee_id_master_employee"),
        ),
        sa.PrimaryKeyConstraint(
            "employee_id", "iso_weekday", name=op.f("pk_master_employee_work_pattern")
        ),
    )
    op.create_table(
        "master_workspace_assignment",
        sa.Column("assignment_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["master_employee.employee_id"],
            name=op.f("fk_master_workspace_assignment_employee_id_master_employee"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["master_workspace.workspace_id"],
            name=op.f("fk_master_workspace_assignment_workspace_id_master_workspace"),
        ),
        sa.PrimaryKeyConstraint("assignment_id", name=op.f("pk_master_workspace_assignment")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("master_workspace_assignment")
    op.drop_table("master_employee_work_pattern")
    with op.batch_alter_table("master_workspace", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_workspace_zone_id"))
        batch_op.drop_index(batch_op.f("ix_master_workspace_floor_id"))

    op.drop_table("master_workspace")
    op.drop_table("master_team_zone_allocation")
    with op.batch_alter_table("master_sensor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_sensor_target_id"))
        batch_op.drop_index(batch_op.f("ix_master_sensor_floor_id"))

    op.drop_table("master_sensor")
    with op.batch_alter_table("master_room", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_room_floor_id"))

    op.drop_table("master_room")
    with op.batch_alter_table("master_employee", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_employee_team_id"))
        batch_op.drop_index("ix_master_employee_home_floor")
        batch_op.drop_index(batch_op.f("ix_master_employee_department_id"))

    op.drop_table("master_employee")
    op.drop_table("sim_run_speed_change")
    op.drop_table("sim_run_metrics_snapshot")
    with op.batch_alter_table("master_zone", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_master_zone_floor_id"))

    op.drop_table("master_zone")
    op.drop_table("master_team")
    op.drop_table("master_access_point")
    op.drop_table("sim_simulation_run")
    op.drop_table("master_floor")
    op.drop_table("ops_pipeline_layer_count")
    op.drop_table("master_building")
    op.drop_table("config_master_data_version")
    op.drop_table("ops_source_status_snapshot")
    op.drop_table("ops_pipeline_run")
    op.drop_table("ops_ingestion_watermark")
    op.drop_table("master_organization")
    op.drop_table("master_department")
    with op.batch_alter_table("config_office_configuration", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_config_office_configuration_content_hash"))

    op.drop_table("config_office_configuration")
    # ### end Alembic commands ###
