"""readers restricted zones devices snapshots

Revision ID: 0003_readers_restricted_snapshots
Revises: 0002_master_config_sim_ops
Create Date: 2026-09-26 02:44:39.131891
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_readers_restricted_snapshots"
down_revision: str | None = "0002_master_config_sim_ops"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sim_floor_snapshot",
        sa.Column("simulation_run_id", sa.String(length=36), nullable=False),
        sa.Column("floor_id", sa.String(), nullable=False),
        sa.Column("sim_minute", sa.DateTime(timezone=True), nullable=False),
        sa.Column("desks", sa.JSON(), nullable=False),
        sa.Column("rooms", sa.JSON(), nullable=False),
        sa.Column("zones", sa.JSON(), nullable=False),
        sa.Column("kpis", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_run_id"],
            ["sim_simulation_run.simulation_run_id"],
            name=op.f("fk_sim_floor_snapshot_simulation_run_id_sim_simulation_run"),
        ),
        sa.PrimaryKeyConstraint(
            "simulation_run_id", "floor_id", "sim_minute", name=op.f("pk_sim_floor_snapshot")
        ),
    )
    op.create_table(
        "master_zone_access_rule",
        sa.Column("zone_id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["master_team.team_id"],
            name=op.f("fk_master_zone_access_rule_team_id_master_team"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["master_zone.zone_id"],
            name=op.f("fk_master_zone_access_rule_zone_id_master_zone"),
        ),
        sa.PrimaryKeyConstraint("zone_id", "team_id", name=op.f("pk_master_zone_access_rule")),
    )
    with op.batch_alter_table("master_access_point", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reader_type", sa.String(), server_default="BUILDING_ENTRANCE", nullable=False
            )
        )
        batch_op.add_column(sa.Column("target_id", sa.String(), server_default="", nullable=False))

    with op.batch_alter_table("master_room", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("has_badge_reader", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.add_column(
            sa.Column("has_panel", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    with op.batch_alter_table("master_workspace", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("device_type", sa.String(), server_default="DOCKING_STATION", nullable=False)
        )

    with op.batch_alter_table("master_zone", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_restricted", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("master_zone", schema=None) as batch_op:
        batch_op.drop_column("is_restricted")

    with op.batch_alter_table("master_workspace", schema=None) as batch_op:
        batch_op.drop_column("device_type")

    with op.batch_alter_table("master_room", schema=None) as batch_op:
        batch_op.drop_column("has_panel")
        batch_op.drop_column("has_badge_reader")

    with op.batch_alter_table("master_access_point", schema=None) as batch_op:
        batch_op.drop_column("target_id")
        batch_op.drop_column("reader_type")

    op.drop_table("master_zone_access_rule")
    op.drop_table("sim_floor_snapshot")
    # ### end Alembic commands ###
